### ISSUE TITLE
Push the shared image to a shared location

### ISSUE THREAD

**Issue by trstringer** [3DStreamingToolkit/cloud-deploy#14]
Once the golden VM image is completed and checked off, it should be placed in a central/shared location so that the orchestrator can consume the image dynamically.

This will take coordination between the developers working on the image and the orchestrator.

**Comment by anderm** [comment]
With the Azure Batch features, we can switch to using the Application model and remove the need of a custom image. We will use pre-built images and deploy our application stack on top of that. See [milestone/5](https://github.com/3DStreamingToolkit/cloud-deploy/milestone/5) and [milestone/6](https://github.com/3DStreamingToolkit/cloud-deploy/milestone/6)
