### ISSUE TITLE
Modify signaling state abstractions to support database interaction

### ISSUE THREAD

**Issue by bengreenier** [3DStreamingToolkit/cloud-deploy#19]
Today, [signaling](https://github.com/bengreenier/3dtoolkit-signal) represents state information (namely the data about which peers are connected and alive) to an in memory object. We should support paging that information out to a database.

Done is defined as:

- [ ] Database access is possible
- [ ] In memory access is possible
- [ ] State can be deterministic-ally paged to database
- [ ] New abstractions tested

**Comment by bengreenier** [comment]
We want to page this information in response to determining a valid pair of peers (one client, and open server with a free slot).

**Comment by anderm** [comment]
No longer required
