### ISSUE TITLE
signaling should inform orchestration of state

### ISSUE THREAD

**Issue by bengreenier** [3DStreamingToolkit/cloud-deploy#41]
We should support posting from signaling to orchestration so that orchestration can consume some signal that tells it how to spin up and down. currently the plan is to issue the following web request when state changes from signaling to orchestration:

```
POST /<whatever>

{
    "totalSessions": number,
    "totalSlots": number,
    "servers": {
        "<id>": {
            "sessions": number,
            "slots": number
        },
        ...
    }
}
```

+ Where "servers" object can be dropped when running in optimized mode (behind a feature flag)
+ Where "totalSessions" is the total active session count
+ Where "totalSlots" is the total active slots available for new sessions
+ Where "servers[id][sessions]" is the total sessions on that server
+ Where "servers[id][slots]" is the total slots available for new sessions on that server

**Comment by bengreenier** [comment]
I'm proposing a modification to the above since it'll be do-able with existing tracked data:

```
POST /<whatever>

{
    "totalClients": number,
    "totalSlots": number,
    "servers": {
        "<id>": {
            "slots": number
        },
        ...
    }
}
```

Where "totalClients" is the total active clients count. 
We drop `servers[id][sessions]` but i bet we don't have a need to calculate demand per-server (we'll likely use the total anyway) so just current available slots should be sufficient.

We drop `totalSessions` and instead provide total clients, so we can estimate growth by tracking the change in `totalClients` over time. Seems that the crux of the problem is solved with `totalSlots` on it's own.

@anderm let me know if you see any issue with this change.

**Comment by anderm** [comment]
Closed with https://github.com/3DStreamingToolkit/signal-3dstk/pull/13
