### ISSUE TITLE
Validate data retrieved from Cosmos 

### ISSUE THREAD

**Issue by gavination** [3DStreamingToolkit/cloud-deploy#9]
- [ ] determine if new VM pool needs to be instanced
- [ ] determine if VM pool to be scaled down  
- [ ] determine if clients need to be sent to Queue
- [ ] make sure that if there's already a pending request in cassandra (marked as pending) that you don't send for another request for the same thing
- [ ] tests

**Comment by anderm** [comment]
Closing as the Orchestrator is managed by Azure Batch
